type User @table {
  username: String!
  email: String!
  createdAt: Timestamp! @default(expr: "request.time")
  displayName: String
  profilePictureUrl: String
}

type Channel @table {
  name: String!
  isPrivate: Boolean!
  createdAt: Timestamp! @default(expr: "request.time")
  description: String
  owner: User!
}

type ChannelMembership @table(key: ["user", "channel"]) {
  user: User!
  channel: Channel!
  joinedAt: Timestamp! @default(expr: "request.time")
}

type Message @table {
  content: String!
  createdAt: Timestamp! @default(expr: "request.time")
  editedAt: Timestamp
  author: User!
  channel: Channel
}

type DirectMessageConversation @table {
  createdAt: Timestamp! @default(expr: "request.time")
  user1: User!
  user2: User!
}

type DirectMessage @table {
  content: String!
  createdAt: Timestamp! @default(expr: "request.time")
  editedAt: Timestamp
  sender: User!
  conversation: DirectMessageConversation!
}

type FileAsset @table {
  name: String!
  size: String!
  type: String!
  url: String!
  uploadedAt: Timestamp! @default(expr: "request.time")
  owner: User!
}

type HuddlePresence @table(key: ["user", "channel"]) {
  user: User!
  channel: Channel!
  joinedAt: Timestamp! @default(expr: "request.time")
}
